version: '3.8'
services:

    # Application
    app:
        build:
            context: .
            dockerfile: ./docker/app.dockerfile
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - "mysql"
    # Web Server
    nginx:
      image: 'nginx:alpine'
      ports:
        - '${APP_PORT:-80}:80'
      volumes:
        - '.:/var/www/html'
        - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
        - './docker/nginx/conf.d:/etc/nginx/conf.d'
      depends_on:
        - app
    # Database
    mysql:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - "3306:3306"
    # Database management
    pma:
        image: phpmyadmin:5.1
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_PORT=${DB_PORT}
        depends_on:
            - mysql
        ports:
            - 8080:80
    # # Mailing Server
    # mailhog:
    #     image: mailhog/mailhog
    #     logging:
    #         driver: 'none'
    #     ports:
    #         - 1025:1025
    #         - 8025:8025

volumes:
    dbdata:
